#!/bin/bash

less << __EOF__
# 半角全角変換 http://nanasi.jp/articles/vim/hz_ja_vim.html
## ビジュアルモードでの全角半角変換
gHL	可能な文字を全て半角に変換する
gZL	可能な文字を全て全角に変換する
gHA	ASCII文字を全て半角に変換する
gHH	ASCII文字を全て半角に変換する
gZA	ASCII文字を全て全角に変換する
gHM	記号を全て半角に変換する
gZM	記号を全て全角に変換する
gHW	英数字を全て半角に変換する
gZW	英数字を全て全角に変換する
gHJ	カタカナを全て半角に変換する
gZJ	カタカナを全て全角に変換する
gZZ	カタカナを全て全角に変換する

__EOF__
